# Generated by Django 5.0.3 on 2024-03-06 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_task_created_at_alter_task_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        related_name="project", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "task_list",
                    models.ManyToManyField(related_name="project", to="dashboard.task"),
                ),
            ],
        ),
    ]
